// <auto-generated />
namespace Pluralsight_sql_injection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290826554_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
